### ISSUE TITLE
Data augmentation techniques used in nuScenes dataloader

### ISSUE THREAD

**Issue by WEIJIARONG99** [hzykent/LiDAL#3]
Dear author:

Thank you for your excellent work!
I have a place that do not quite understand. In the nu_dataset.py file, for data augmentation, you multiply the coords_p by self.scale (20). Normally from what I know, the scaling factor should be set to around 0.95-1.05 or something alike. Is there some special data augmentation tricks here?

Best regards
Jiarong

**Comment by hzykent** [comment]
Hi Jiarong,

Thanks for your interest.

The scaling factor here refers to the voxelization process. e.g., 20 refers to 1/20 = 0.05 m voxel size and 50 refers to 1/50 = 0.02 m voxel size.

Hope this could clear up your doubts.

Cheers,
Zeyu

**Comment by WEIJIARONG99** [comment]
It's clear now. Thanks!
